---
blank_issues_enabled: false
contact_links:
  - name: ðŸ’µ Donate
    url: https://html-preview.github.io/?url=https://raw.githubusercontent.com/apersongithub/Duoblock-Origin/refs/heads/main/extras/donations.html
    about: give me money here